apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: ${{ values.description | dump }}
spec:
  type: dataproduct
  lifecycle: experimental
  owner: ${{ values.dataProductOwner }}
  mesh:
    email: ${{ values.email | dump }}
    informationSLA: ${{ values.informationSLA | dump }}
    maturity: ${{ values.maturity | dump }}
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
