apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: dataproduct-template
  title: Data Product Template
  description: Create a repository containing the definition of a Data Product
  tags:
    - data-product
spec:
  owner: agilelab
  type: dataproduct
  
  parameters:
    - title: Data Product details
      required:
        - name
        - description
        - domain
        - version
        - owner
        - email
      properties:
        name:
          title: Data Product name
          type: string
          description: the Data Product name
        fullyQualifiedName:
          title: Fully Qualified Name
          type: string
          description: Human-readable that uniquely identifies an entity
        displayName:
          title: Display Name
          type: string
          description: Optional name used for display purposes
        description:
          title: Description
          type: string
          description: Help others understand what this Data Product is for.
        domain:
          title: Domain
          type: string
          description: the Domain of the Data Product
          ui:field: EntityPicker
          ui:options:
            allowedKinds: 
              - Domain
        version:
          title: Version
          type: string
          description: the version of the Data Product
          default: "0.0.0"
        owner:
          title: Owner
          type: string
          description: Owner of the Data Product
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
        email:
          title: Contact email
          type: string
          description:  Point of contact
        informationSLA: 
          title: InformationSLA
          type: string
          description: Describe what SLA the DP team is providing to answer additional information requests about the DP
        status: 
          title: Status
          type: string
          description: status of this version of the DP
          enum:
            - Draft
            - Published
            - Retired
        maturity:
          title: Maturity
          type: string
          description: Understand if it is a tactical solution or not
          enum:
            - Tactical
            - Strategic
    - title: Choose a location  
      required:
        - repoUrl
      properties: 
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .gitlab-ci.yml
        values:
          domain: '{{ parameters.domain }}'
          name: '{{ parameters.name }}'
          version: '{{ parameters.version }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          description: '{{ parameters.description }}'
          owner: '{{ parameters.owner }}'
          email: '{{ parameters.email }}'
          fullyQualifiedName: '{{ parameters.fullyQualifiedName }}'
          displayName: '{{ parameters.displayName }}'
          informationSLA: '{{ parameters.informationSLA }}'
          status: '{{ parameters.status }}'
          maturity: '{{ parameters.maturity }}'
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
