apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.name + "-" + values.version}}
  description: ${{values.description | dump}}
  annotations:
    gitlab.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: dataproduct
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  domain: ${{values.domain | dump}}
  mesh:
    id: ${{values.domain + "." + values.name + "." + values.version}}
    version: ${{ values.version | dump}}
    email: ${{ values.email | dump }}
    fullyQualifiedName: ${{ values.fullyQualifiedName | dump }}
    displayName: ${{ values.displayName | dump }}
    informationSLA: ${{ values.informationSLA | dump }}
    status: ${{ values.status | dump }}
    maturity: ${{ values.maturity | dump }}
    billing: {}
    tags: []
    specific: {}
