apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values['domain'].slice(7) + "-" + values.name + "-" + "0" }}
  description: ${{ values.description | dump }}
  annotations:
    gitlab.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: dataproduct
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
  domain: ${{ values.domain | dump }}
  mesh:
    email: ${{ values.email | dump }}
    version: 0.0.0
    fullyQualifiedName: ${{ values.fullyQualifiedName | dump }}
    displayName: ${{ values.displayName | dump }}
    informationSLA: ${{ values.informationSLA | dump }}
    maturity: ${{ values.maturity | dump }}
    billing: {}
    tags: []
    specific: {}
