apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.identifier  }}
  description: ${{ values.description | dump }}
  annotations:
    gitlab.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: dataproduct
  lifecycle: experimental
  owner: ${{ values.dataProductOwner }}
  domain: ${{ values.domain | dump }}
  mesh:
    dataProductOwner: ${{ values.dataProductOwner }}
    devGroup: ${{ values.devGroup }}
    email: ${{ values.email | dump }}
    version: 0.0.0
    fullyQualifiedName: ${{ values.fullyQualifiedName | dump }}
    name: ${{ values.name | dump }}
    informationSLA: ${{ values.informationSLA | dump }}
    maturity: ${{ values.maturity | dump }}
    useCaseTemplateId: ${{ values.useCaseTemplateId | dump }}
    infrastructureTemplateId: ${{ values.infrastructureTemplateId | dump }}
    billing: {}
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    specific: {}
